apiVersion: v1
kind: Pod
metadata:
  name: module-controller
  labels:
    app: module-controller
spec:
  serviceAccountName: virtual-kubelet
  containers:
    - name: module-controller
      image: serverless-registry.cn-shanghai.cr.aliyuncs.com/opensource/release/module_controller:0.2.0
      imagePullPolicy: Always
      resources:
        limits:
          cpu: "1000m"
          memory: "400Mi"
      env:
        - name: MQTT_BROKER # mqtt broker url
          value: YOUR_MQTT_BROKER_ENDPOINT
        - name: MQTT_PORT # mqtt port
          value: YOUR_MQTT_PORT
        - name: MQTT_USERNAME # mqtt username
          value: YOUR_MQTT_USERNAME
        - name: MQTT_PASSWORD # mqtt password
          value: YOUR_MQTT_PASSWORD
        - name: MQTT_CLIENT_PREFIX # mqtt client prefix
          value: YOUR_MQTT_CLIENT_PREFIX
        - name: REPORT_HOOKS # error report hooks, only support dingTalk robot webhook
          value: YOUR_REPORT_HOOKS
        - name: ENV
          value: YOUR_ENV