kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: e2e-test-role
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods" , "pods/status", "pods/spec","nodes", "nodes/status" , "deployments", "daemonSets", "events"]
    verbs: ["get", "watch", "list"]
